draw_set_color(c_black)
//draw_set_color(c_yellow)
//draw_rectangle(global.idealborder[0]-60,global.idealborder[2]-40,global.idealborder[1]+60,global.idealborder[2],false)
//draw_set_color(c_green)
draw_rectangle(global.idealborder[0]-60,global.idealborder[3]+40,global.idealborder[1]+60,global.idealborder[3],false)
//draw_set_color(c_red)
draw_rectangle(0,global.idealborder[2],global.idealborder[0],global.idealborder[3]+40,false)
//draw_set_color(c_blue)
draw_rectangle(640,global.idealborder[2],global.idealborder[1],global.idealborder[3]+40,false)
scr_binfowrite()

