function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // blt_avoidfire
	global.__objectDepths[1] = 0; // blt_blookhat
	global.__objectDepths[2] = 0; // blt_bluespear
	global.__objectDepths[3] = 0; // blt_butterfly1
	global.__objectDepths[4] = 0; // blt_butterfly2
	global.__objectDepths[5] = 0; // blt_chasefire1
	global.__objectDepths[6] = 0; // blt_chasefire2
	global.__objectDepths[7] = 0; // blt_crybullet
	global.__objectDepths[8] = 0; // blt_crybullet2
	global.__objectDepths[9] = 0; // blt_direct
	global.__objectDepths[10] = 0; // blt_firehelix1
	global.__objectDepths[11] = 0; // blt_floatfire
	global.__objectDepths[12] = 0; // blt_flybullet
	global.__objectDepths[13] = 0; // blt_gen
	global.__objectDepths[14] = 0; // blt_gravbullet
	global.__objectDepths[15] = 0; // blt_handbullet1
	global.__objectDepths[16] = 0; // blt_handbullet2
	global.__objectDepths[17] = 0; // blt_hoopbullet1
	global.__objectDepths[18] = 0; // blt_hoopbullet2
	global.__objectDepths[19] = 0; // blt_laser
	global.__objectDepths[20] = 0; // blt_leapfrog
	global.__objectDepths[21] = 0; // blt_minihelix
	global.__objectDepths[22] = 0; // blt_parent
	global.__objectDepths[23] = 0; // blt_pollendrop
	global.__objectDepths[24] = 0; // blt_roachbullet
	global.__objectDepths[25] = 0; // blt_roachdance
	global.__objectDepths[26] = 0; // blt_splinter
	global.__objectDepths[27] = 0; // blt_splinterbig
	global.__objectDepths[28] = 0; // blt_streambullet
	global.__objectDepths[29] = 0; // blt_thatch
	global.__objectDepths[30] = 0; // blt_tinypom_leap
	global.__objectDepths[31] = 0; // blt_vegbullet
	global.__objectDepths[32] = 0; // blt_whitespear
	global.__objectDepths[33] = -450; // obj_1sidegen
	global.__objectDepths[34] = -450; // obj_allaroundgen
	global.__objectDepths[35] = 0; // obj_asrielbed
	global.__objectDepths[36] = 0; // obj_asriellamp
	global.__objectDepths[37] = 0; // obj_basementmusic
	global.__objectDepths[38] = 11; // obj_battlebg
	global.__objectDepths[39] = 0; // obj_battleblcon
	global.__objectDepths[40] = -450; // obj_battlecontroller
	global.__objectDepths[41] = -1000; // obj_battlefader
	global.__objectDepths[42] = -601; // obj_battler
	global.__objectDepths[43] = -601; // obj_battlerflowey
	global.__objectDepths[44] = 0; // obj_bigpie
	global.__objectDepths[45] = 0; // obj_bigweb
	global.__objectDepths[46] = -5; // obj_blackborderer
	global.__objectDepths[47] = 0; // OBJ_BLCON
	global.__objectDepths[48] = 10; // obj_blconsm
	global.__objectDepths[49] = 10; // obj_blconwdflowey
	global.__objectDepths[50] = 29; // obj_blkpxl0tall
	global.__objectDepths[51] = 29; // obj_blkpxlgrav
	global.__objectDepths[52] = 29; // obj_blkpxltall
	global.__objectDepths[53] = 0; // obj_blueswitch_1
	global.__objectDepths[54] = -999; // obj_borderparent
	global.__objectDepths[55] = 2; // obj_btparent
	global.__objectDepths[56] = -450; // obj_bulletgen1
	global.__objectDepths[57] = 0; // obj_bulletgenparent
	global.__objectDepths[58] = -450; // obj_bulletgenthatched
	global.__objectDepths[59] = 0; // obj_butterfly2gen
	global.__objectDepths[60] = 0; // obj_cactus
	global.__objectDepths[61] = 0; // obj_candydish1
	global.__objectDepths[62] = 0; // obj_candydish2
	global.__objectDepths[63] = 999999; // obj_chairiel
	global.__objectDepths[64] = 0; // obj_cheesetable1
	global.__objectDepths[65] = -600; // obj_choicer
	global.__objectDepths[66] = -9999; // obj_cosmeticblcon
	global.__objectDepths[67] = 70000; // obj_cosmetichole
	global.__objectDepths[68] = 29; // obj_coverup
	global.__objectDepths[69] = -450; // obj_crygen1
	global.__objectDepths[70] = -450; // obj_crygen2
	global.__objectDepths[71] = -450; // obj_crygen3
	global.__objectDepths[72] = -999; // obj_dborder
	global.__objectDepths[73] = 0; // obj_demodoorA
	global.__objectDepths[74] = 0; // obj_dialoguer
	global.__objectDepths[75] = 0; // obj_dmgwriter
	global.__objectDepths[76] = 10; // obj_dogeB
	global.__objectDepths[77] = 11; // obj_dogeBtail
	global.__objectDepths[78] = 0; // obj_door_ruins13
	global.__objectDepths[79] = 0; // obj_doorA
	global.__objectDepths[80] = 0; // obj_doorAmusicfade
	global.__objectDepths[81] = 0; // obj_doorB
	global.__objectDepths[82] = 0; // obj_doorBmusicfade
	global.__objectDepths[83] = 0; // obj_doorC
	global.__objectDepths[84] = 0; // obj_doorD
	global.__objectDepths[85] = 0; // obj_doorparent
	global.__objectDepths[86] = 999999; // obj_downstairs
	global.__objectDepths[87] = 0; // obj_dummy1
	global.__objectDepths[88] = 10; // obj_dummymonster
	global.__objectDepths[89] = 0; // obj_dustcloud
	global.__objectDepths[90] = 0; // obj_encounter_ruins1
	global.__objectDepths[91] = 0; // obj_encounter_ruins2
	global.__objectDepths[92] = 0; // obj_encounterer_ruins3
	global.__objectDepths[93] = 0; // obj_encounterer_ruins4
	global.__objectDepths[94] = 0; // obj_encounterer_ruins5
	global.__objectDepths[95] = 0; // obj_encounterer_ruins6
	global.__objectDepths[96] = 0; // obj_encountererparent
	global.__objectDepths[97] = 0; // obj_encountertrigger1
	global.__objectDepths[98] = 0; // obj_exitmarker3
	global.__objectDepths[99] = 0; // obj_face
	global.__objectDepths[100] = -555; // obj_face_floweytalk
	global.__objectDepths[101] = -555; // obj_face_papyrus
	global.__objectDepths[102] = -555; // obj_face_sans
	global.__objectDepths[103] = -557; // obj_face_torglasses
	global.__objectDepths[104] = -555; // obj_face_torielblink
	global.__objectDepths[105] = -555; // obj_face_torieltalk
	global.__objectDepths[106] = -99999; // obj_fader
	global.__objectDepths[107] = 10; // obj_fakefroggit
	global.__objectDepths[108] = 0; // obj_fakeheart
	global.__objectDepths[109] = -400; // obj_fakepellet
	global.__objectDepths[110] = 999999; // obj_fakewater
	global.__objectDepths[111] = 999999; // obj_fakewaterl
	global.__objectDepths[112] = 999999; // obj_fakewaterm
	global.__objectDepths[113] = 999999; // obj_fakewateropenl
	global.__objectDepths[114] = 999999; // obj_fakewateropenm
	global.__objectDepths[115] = 999999; // obj_fakewateropenr
	global.__objectDepths[116] = 999999; // obj_fakewaterr
	global.__objectDepths[117] = 999999; // obj_fakewatershadowl
	global.__objectDepths[118] = 999999; // obj_fakewatershadowm
	global.__objectDepths[119] = 999999; // obj_fakewatershadowr
	global.__objectDepths[120] = 2; // obj_fightbt
	global.__objectDepths[121] = 99999; // obj_finaldoor
	global.__objectDepths[122] = 0; // obj_floface
	global.__objectDepths[123] = 999999; // obj_floorswitch1
	global.__objectDepths[124] = 0; // obj_floweybattle1
	global.__objectDepths[125] = 0; // obj_floweydraw
	global.__objectDepths[126] = 0; // obj_floweytalker1
	global.__objectDepths[127] = 0; // obj_floweytrigger
	global.__objectDepths[128] = 0; // obj_floweytrigger2
	global.__objectDepths[129] = 0; // obj_foodsound
	global.__objectDepths[130] = 20; // obj_friendlypellet
	global.__objectDepths[131] = 10; // obj_froggit
	global.__objectDepths[132] = 6; // obj_froghead
	global.__objectDepths[133] = 7; // obj_froglegs
	global.__objectDepths[134] = 0; // obj_gameover
	global.__objectDepths[135] = 10; // obj_gameoverbg
	global.__objectDepths[136] = 0; // obj_goofyrock
	global.__objectDepths[137] = 0; // obj_greenswitch_1
	global.__objectDepths[138] = 0; // obj_growshrink
	global.__objectDepths[139] = -4000; // obj_guidearrows
	global.__objectDepths[140] = 0; // obj_heart
	global.__objectDepths[141] = 0; // obj_heartdefeated
	global.__objectDepths[142] = 0; // obj_hearthflame
	global.__objectDepths[143] = 0; // obj_heartshard
	global.__objectDepths[144] = 70000; // obj_holedown
	global.__objectDepths[145] = 0; // obj_holedown2
	global.__objectDepths[146] = 70000; // obj_holedown3
	global.__objectDepths[147] = 0; // obj_holeup
	global.__objectDepths[148] = 0; // obj_holeup2
	global.__objectDepths[149] = -450; // obj_hoopgen1
	global.__objectDepths[150] = 0; // obj_housemusic
	global.__objectDepths[151] = -99; // obj_hpname
	global.__objectDepths[152] = -500; // OBJ_INSTAWRITER
	global.__objectDepths[153] = 0; // obj_interactable
	global.__objectDepths[154] = -99999; // obj_introfader
	global.__objectDepths[155] = 0; // obj_introimage
	global.__objectDepths[156] = 0; // obj_introlast
	global.__objectDepths[157] = 0; // obj_intromenu
	global.__objectDepths[158] = -400; // obj_introtangle
	global.__objectDepths[159] = 2; // obj_itembt
	global.__objectDepths[160] = 0; // obj_kitchentable
	global.__objectDepths[161] = 0; // obj_knife_pickup
	global.__objectDepths[162] = -450; // obj_lasergen1
	global.__objectDepths[163] = -999; // obj_lborder
	global.__objectDepths[164] = 0; // obj_lchair
	global.__objectDepths[165] = 10; // obj_loox
	global.__objectDepths[166] = 100; // obj_mainchara
	global.__objectDepths[167] = 0; // obj_markerA
	global.__objectDepths[168] = 0; // obj_markerB
	global.__objectDepths[169] = 0; // obj_markerC
	global.__objectDepths[170] = 0; // obj_markerD
	global.__objectDepths[171] = 0; // obj_markerX
	global.__objectDepths[172] = 0; // obj_menumusictest
	global.__objectDepths[173] = 10; // obj_migosp
	global.__objectDepths[174] = 2000000; // obj_mirrorreflection
	global.__objectDepths[175] = 10; // obj_moldsmal
	global.__objectDepths[176] = 0; // obj_monsterparent
	global.__objectDepths[177] = 99999; // obj_mousehole
	global.__objectDepths[178] = 0; // obj_musfadein
	global.__objectDepths[179] = 0; // obj_musfadeout
	global.__objectDepths[180] = 0; // obj_musicchecker
	global.__objectDepths[181] = 10; // obj_napstablook
	global.__objectDepths[182] = 0; // obj_napstablook1
	global.__objectDepths[183] = 0; // obj_napstablook2
	global.__objectDepths[184] = 99999; // obj_nastrytree_bottom
	global.__objectDepths[185] = 0; // obj_nastytree
	global.__objectDepths[186] = -500; // OBJ_NOMSCWRITER
	global.__objectDepths[187] = 0; // obj_npc_marker
	global.__objectDepths[188] = 100; // obj_npctest
	global.__objectDepths[189] = -500; // obj_overworldcontroller
	global.__objectDepths[190] = 0; // obj_papyrussign
	global.__objectDepths[191] = 400000; // obj_pbflame
	global.__objectDepths[192] = -99999; // obj_persistentfader
	global.__objectDepths[193] = 0; // obj_pie_pickup
	global.__objectDepths[194] = 0; // obj_pillar_1
	global.__objectDepths[195] = 0; // obj_plotswitch1
	global.__objectDepths[196] = 0; // obj_plotswitch2
	global.__objectDepths[197] = 0; // obj_plotswitch3
	global.__objectDepths[198] = 0; // obj_plotwall_room
	global.__objectDepths[199] = 0; // obj_plotwall1
	global.__objectDepths[200] = 0; // obj_plotwall2
	global.__objectDepths[201] = 0; // obj_plotwall3
	global.__objectDepths[202] = 0; // obj_plotwall4
	global.__objectDepths[203] = 0; // obj_plotwall5
	global.__objectDepths[204] = 0; // obj_plotwall6
	global.__objectDepths[205] = 0; // obj_pushrock1
	global.__objectDepths[206] = 0; // obj_pushrock2
	global.__objectDepths[207] = 0; // obj_pushrock3
	global.__objectDepths[208] = -999999; // obj_quittingmessage
	global.__objectDepths[209] = 0; // obj_radialfakegen
	global.__objectDepths[210] = 0; // obj_radialfakegenx
	global.__objectDepths[211] = -999; // obj_rborder
	global.__objectDepths[212] = 0; // obj_rchair
	global.__objectDepths[213] = 0; // obj_readable
	global.__objectDepths[214] = 0; // obj_readable_flowers1
	global.__objectDepths[215] = 0; // obj_readable_plaque_1
	global.__objectDepths[216] = 0; // obj_readable_plaque_2
	global.__objectDepths[217] = 0; // obj_readable_room1
	global.__objectDepths[218] = 0; // obj_readable_room2
	global.__objectDepths[219] = 0; // obj_readable_room3
	global.__objectDepths[220] = 0; // obj_readable_room4
	global.__objectDepths[221] = 0; // obj_readable_sign1
	global.__objectDepths[222] = 0; // obj_readable_sign2
	global.__objectDepths[223] = 0; // obj_readable_switch1
	global.__objectDepths[224] = 0; // obj_readablesolid
	global.__objectDepths[225] = 0; // obj_redswitch_1
	global.__objectDepths[226] = 0; // obj_ribbon_pickup
	global.__objectDepths[227] = 0; // obj_rock_activator
	global.__objectDepths[228] = 0; // obj_rotategen
	global.__objectDepths[229] = 999999; // obj_ruinsdoor1
	global.__objectDepths[230] = 0; // obj_ruinsmusic
	global.__objectDepths[231] = 1; // obj_sadmsggen
	global.__objectDepths[232] = 0; // obj_sansbox
	global.__objectDepths[233] = 0; // obj_savepoint
	global.__objectDepths[234] = 0; // obj_screen
	global.__objectDepths[235] = 60000; // obj_sdl
	global.__objectDepths[236] = 60000; // obj_sdr
	global.__objectDepths[237] = 0; // obj_shaker
	global.__objectDepths[238] = 0; // obj_sign_room
	global.__objectDepths[239] = 0; // obj_slice
	global.__objectDepths[240] = 0; // obj_smallchair
	global.__objectDepths[241] = 0; // obj_smallfrog
	global.__objectDepths[242] = 0; // obj_smallweb
	global.__objectDepths[243] = 0; // obj_sockdrawer
	global.__objectDepths[244] = 60000; // obj_solidlong
	global.__objectDepths[245] = 0; // obj_solidnpcparent
	global.__objectDepths[246] = 0; // obj_solidparent
	global.__objectDepths[247] = 0; // obj_solidrailing
	global.__objectDepths[248] = 0; // obj_solidrailing2
	global.__objectDepths[249] = 0; // obj_solidrailing3
	global.__objectDepths[250] = 60000; // obj_solidsmall
	global.__objectDepths[251] = 60000; // obj_solidtall
	global.__objectDepths[252] = 60000; // obj_solidwide
	global.__objectDepths[253] = 2; // obj_sparebt
	global.__objectDepths[254] = 25; // obj_spared
	global.__objectDepths[255] = 2; // obj_spellbt
	global.__objectDepths[256] = 999999; // obj_spikes_room
	global.__objectDepths[257] = 999999; // obj_spiketile1
	global.__objectDepths[258] = 999999; // obj_spiketile2
	global.__objectDepths[259] = 0; // obj_staircollission
	global.__objectDepths[260] = 0; // obj_stairstep
	global.__objectDepths[261] = 0; // obj_stalkerflowey
	global.__objectDepths[262] = 0; // obj_storagemenu
	global.__objectDepths[263] = 60000; // obj_sul
	global.__objectDepths[264] = 60000; // obj_sur
	global.__objectDepths[265] = 0; // obj_switchadvice1
	global.__objectDepths[266] = 0; // obj_switchadvice2
	global.__objectDepths[267] = 0; // obj_switchbasic
	global.__objectDepths[268] = 0; // obj_switchhelptrigger
	global.__objectDepths[269] = 2; // obj_talkbt
	global.__objectDepths[270] = 0; // obj_target
	global.__objectDepths[271] = -2; // obj_targetchoice
	global.__objectDepths[272] = 0; // obj_targetchoiceHITSEVERYONE
	global.__objectDepths[273] = -198; // obj_tempblack
	global.__objectDepths[274] = 10; // obj_testmonster
	global.__objectDepths[275] = 0; // obj_theartshard
	global.__objectDepths[276] = 0; // obj_time
	global.__objectDepths[277] = 0; // obj_titleimage
	global.__objectDepths[278] = -500; // obj_torbody
	global.__objectDepths[279] = 0; // obj_torface
	global.__objectDepths[280] = 9; // obj_torgen
	global.__objectDepths[281] = 0; // obj_torgen_house1
	global.__objectDepths[282] = 0; // obj_torhandhold1
	global.__objectDepths[283] = 45; // obj_torheart
	global.__objectDepths[284] = 10; // obj_torielboss
	global.__objectDepths[285] = 0; // obj_torielcall1
	global.__objectDepths[286] = 0; // obj_torielcall2
	global.__objectDepths[287] = 0; // obj_torielcall3
	global.__objectDepths[288] = 0; // obj_torielcall4
	global.__objectDepths[289] = 0; // obj_torielcall5
	global.__objectDepths[290] = 0; // obj_torielcutscene
	global.__objectDepths[291] = 0; // obj_torieldisapprove
	global.__objectDepths[292] = 0; // obj_torielflame_X
	global.__objectDepths[293] = 0; // obj_torieltrigger1
	global.__objectDepths[294] = 0; // obj_torieltrigger10
	global.__objectDepths[295] = 0; // obj_torieltrigger11
	global.__objectDepths[296] = 0; // obj_torieltrigger12
	global.__objectDepths[297] = 0; // obj_torieltrigger2
	global.__objectDepths[298] = 0; // obj_torieltrigger3
	global.__objectDepths[299] = 0; // obj_torieltrigger4
	global.__objectDepths[300] = 0; // obj_torieltrigger5
	global.__objectDepths[301] = 0; // obj_torieltrigger6
	global.__objectDepths[302] = 0; // obj_torieltrigger7
	global.__objectDepths[303] = 0; // obj_torieltrigger8
	global.__objectDepths[304] = 0; // obj_torieltrigger9
	global.__objectDepths[305] = 0; // obj_torinteractable1
	global.__objectDepths[306] = 0; // obj_torinteractable2
	global.__objectDepths[307] = 0; // obj_torinteractable3
	global.__objectDepths[308] = 0; // obj_torinteractable4
	global.__objectDepths[309] = 0; // obj_torinteractable5
	global.__objectDepths[310] = 0; // obj_torinteractable6
	global.__objectDepths[311] = 0; // obj_torinteractable7
	global.__objectDepths[312] = 0; // obj_toroverworld1
	global.__objectDepths[313] = 0; // obj_toroverworld2
	global.__objectDepths[314] = 0; // obj_toroverworld3
	global.__objectDepths[315] = 0; // obj_toroverworld4
	global.__objectDepths[316] = 0; // obj_toroverworld5
	global.__objectDepths[317] = 0; // obj_toroverworld6
	global.__objectDepths[318] = 0; // obj_toroverworld7
	global.__objectDepths[319] = -600; // obj_transheart
	global.__objectDepths[320] = 0; // obj_transitioner
	global.__objectDepths[321] = -999; // obj_uborder
	global.__objectDepths[322] = 0; // obj_uchair
	global.__objectDepths[323] = 0; // obj_undertaletitle
	global.__objectDepths[324] = -99999; // obj_unfader
	global.__objectDepths[325] = 50; // obj_vaporacquirer
	global.__objectDepths[326] = 50; // obj_vaporized
	global.__objectDepths[327] = 50; // obj_vaporized_old
	global.__objectDepths[328] = 25; // obj_vaporizedspare
	global.__objectDepths[329] = 10; // obj_vegetoid
	global.__objectDepths[330] = 0; // obj_vegetoid_overworld
	global.__objectDepths[331] = 999999; // obj_wallswitchcut1
	global.__objectDepths[332] = 100; // obj_wanderparent
	global.__objectDepths[333] = 10; // obj_whimsun
	global.__objectDepths[334] = -99999; // obj_whitefader
	global.__objectDepths[335] = 20; // obj_whtpxlgrav
	global.__objectDepths[336] = -200; // obj_winkstar
	global.__objectDepths[337] = -500; // OBJ_WRITER
	global.__objectDepths[338] = 0; // OBJ_WRITERCREATOR
	global.__objectDepths[339] = 0; // object59


	global.__objectNames[0] = "blt_avoidfire";
	global.__objectNames[1] = "blt_blookhat";
	global.__objectNames[2] = "blt_bluespear";
	global.__objectNames[3] = "blt_butterfly1";
	global.__objectNames[4] = "blt_butterfly2";
	global.__objectNames[5] = "blt_chasefire1";
	global.__objectNames[6] = "blt_chasefire2";
	global.__objectNames[7] = "blt_crybullet";
	global.__objectNames[8] = "blt_crybullet2";
	global.__objectNames[9] = "blt_direct";
	global.__objectNames[10] = "blt_firehelix1";
	global.__objectNames[11] = "blt_floatfire";
	global.__objectNames[12] = "blt_flybullet";
	global.__objectNames[13] = "blt_gen";
	global.__objectNames[14] = "blt_gravbullet";
	global.__objectNames[15] = "blt_handbullet1";
	global.__objectNames[16] = "blt_handbullet2";
	global.__objectNames[17] = "blt_hoopbullet1";
	global.__objectNames[18] = "blt_hoopbullet2";
	global.__objectNames[19] = "blt_laser";
	global.__objectNames[20] = "blt_leapfrog";
	global.__objectNames[21] = "blt_minihelix";
	global.__objectNames[22] = "blt_parent";
	global.__objectNames[23] = "blt_pollendrop";
	global.__objectNames[24] = "blt_roachbullet";
	global.__objectNames[25] = "blt_roachdance";
	global.__objectNames[26] = "blt_splinter";
	global.__objectNames[27] = "blt_splinterbig";
	global.__objectNames[28] = "blt_streambullet";
	global.__objectNames[29] = "blt_thatch";
	global.__objectNames[30] = "blt_tinypom_leap";
	global.__objectNames[31] = "blt_vegbullet";
	global.__objectNames[32] = "blt_whitespear";
	global.__objectNames[33] = "obj_1sidegen";
	global.__objectNames[34] = "obj_allaroundgen";
	global.__objectNames[35] = "obj_asrielbed";
	global.__objectNames[36] = "obj_asriellamp";
	global.__objectNames[37] = "obj_basementmusic";
	global.__objectNames[38] = "obj_battlebg";
	global.__objectNames[39] = "obj_battleblcon";
	global.__objectNames[40] = "obj_battlecontroller";
	global.__objectNames[41] = "obj_battlefader";
	global.__objectNames[42] = "obj_battler";
	global.__objectNames[43] = "obj_battlerflowey";
	global.__objectNames[44] = "obj_bigpie";
	global.__objectNames[45] = "obj_bigweb";
	global.__objectNames[46] = "obj_blackborderer";
	global.__objectNames[47] = "OBJ_BLCON";
	global.__objectNames[48] = "obj_blconsm";
	global.__objectNames[49] = "obj_blconwdflowey";
	global.__objectNames[50] = "obj_blkpxl0tall";
	global.__objectNames[51] = "obj_blkpxlgrav";
	global.__objectNames[52] = "obj_blkpxltall";
	global.__objectNames[53] = "obj_blueswitch_1";
	global.__objectNames[54] = "obj_borderparent";
	global.__objectNames[55] = "obj_btparent";
	global.__objectNames[56] = "obj_bulletgen1";
	global.__objectNames[57] = "obj_bulletgenparent";
	global.__objectNames[58] = "obj_bulletgenthatched";
	global.__objectNames[59] = "obj_butterfly2gen";
	global.__objectNames[60] = "obj_cactus";
	global.__objectNames[61] = "obj_candydish1";
	global.__objectNames[62] = "obj_candydish2";
	global.__objectNames[63] = "obj_chairiel";
	global.__objectNames[64] = "obj_cheesetable1";
	global.__objectNames[65] = "obj_choicer";
	global.__objectNames[66] = "obj_cosmeticblcon";
	global.__objectNames[67] = "obj_cosmetichole";
	global.__objectNames[68] = "obj_coverup";
	global.__objectNames[69] = "obj_crygen1";
	global.__objectNames[70] = "obj_crygen2";
	global.__objectNames[71] = "obj_crygen3";
	global.__objectNames[72] = "obj_dborder";
	global.__objectNames[73] = "obj_demodoorA";
	global.__objectNames[74] = "obj_dialoguer";
	global.__objectNames[75] = "obj_dmgwriter";
	global.__objectNames[76] = "obj_dogeB";
	global.__objectNames[77] = "obj_dogeBtail";
	global.__objectNames[78] = "obj_door_ruins13";
	global.__objectNames[79] = "obj_doorA";
	global.__objectNames[80] = "obj_doorAmusicfade";
	global.__objectNames[81] = "obj_doorB";
	global.__objectNames[82] = "obj_doorBmusicfade";
	global.__objectNames[83] = "obj_doorC";
	global.__objectNames[84] = "obj_doorD";
	global.__objectNames[85] = "obj_doorparent";
	global.__objectNames[86] = "obj_downstairs";
	global.__objectNames[87] = "obj_dummy1";
	global.__objectNames[88] = "obj_dummymonster";
	global.__objectNames[89] = "obj_dustcloud";
	global.__objectNames[90] = "obj_encounter_ruins1";
	global.__objectNames[91] = "obj_encounter_ruins2";
	global.__objectNames[92] = "obj_encounterer_ruins3";
	global.__objectNames[93] = "obj_encounterer_ruins4";
	global.__objectNames[94] = "obj_encounterer_ruins5";
	global.__objectNames[95] = "obj_encounterer_ruins6";
	global.__objectNames[96] = "obj_encountererparent";
	global.__objectNames[97] = "obj_encountertrigger1";
	global.__objectNames[98] = "obj_exitmarker3";
	global.__objectNames[99] = "obj_face";
	global.__objectNames[100] = "obj_face_floweytalk";
	global.__objectNames[101] = "obj_face_papyrus";
	global.__objectNames[102] = "obj_face_sans";
	global.__objectNames[103] = "obj_face_torglasses";
	global.__objectNames[104] = "obj_face_torielblink";
	global.__objectNames[105] = "obj_face_torieltalk";
	global.__objectNames[106] = "obj_fader";
	global.__objectNames[107] = "obj_fakefroggit";
	global.__objectNames[108] = "obj_fakeheart";
	global.__objectNames[109] = "obj_fakepellet";
	global.__objectNames[110] = "obj_fakewater";
	global.__objectNames[111] = "obj_fakewaterl";
	global.__objectNames[112] = "obj_fakewaterm";
	global.__objectNames[113] = "obj_fakewateropenl";
	global.__objectNames[114] = "obj_fakewateropenm";
	global.__objectNames[115] = "obj_fakewateropenr";
	global.__objectNames[116] = "obj_fakewaterr";
	global.__objectNames[117] = "obj_fakewatershadowl";
	global.__objectNames[118] = "obj_fakewatershadowm";
	global.__objectNames[119] = "obj_fakewatershadowr";
	global.__objectNames[120] = "obj_fightbt";
	global.__objectNames[121] = "obj_finaldoor";
	global.__objectNames[122] = "obj_floface";
	global.__objectNames[123] = "obj_floorswitch1";
	global.__objectNames[124] = "obj_floweybattle1";
	global.__objectNames[125] = "obj_floweydraw";
	global.__objectNames[126] = "obj_floweytalker1";
	global.__objectNames[127] = "obj_floweytrigger";
	global.__objectNames[128] = "obj_floweytrigger2";
	global.__objectNames[129] = "obj_foodsound";
	global.__objectNames[130] = "obj_friendlypellet";
	global.__objectNames[131] = "obj_froggit";
	global.__objectNames[132] = "obj_froghead";
	global.__objectNames[133] = "obj_froglegs";
	global.__objectNames[134] = "obj_gameover";
	global.__objectNames[135] = "obj_gameoverbg";
	global.__objectNames[136] = "obj_goofyrock";
	global.__objectNames[137] = "obj_greenswitch_1";
	global.__objectNames[138] = "obj_growshrink";
	global.__objectNames[139] = "obj_guidearrows";
	global.__objectNames[140] = "obj_heart";
	global.__objectNames[141] = "obj_heartdefeated";
	global.__objectNames[142] = "obj_hearthflame";
	global.__objectNames[143] = "obj_heartshard";
	global.__objectNames[144] = "obj_holedown";
	global.__objectNames[145] = "obj_holedown2";
	global.__objectNames[146] = "obj_holedown3";
	global.__objectNames[147] = "obj_holeup";
	global.__objectNames[148] = "obj_holeup2";
	global.__objectNames[149] = "obj_hoopgen1";
	global.__objectNames[150] = "obj_housemusic";
	global.__objectNames[151] = "obj_hpname";
	global.__objectNames[152] = "OBJ_INSTAWRITER";
	global.__objectNames[153] = "obj_interactable";
	global.__objectNames[154] = "obj_introfader";
	global.__objectNames[155] = "obj_introimage";
	global.__objectNames[156] = "obj_introlast";
	global.__objectNames[157] = "obj_intromenu";
	global.__objectNames[158] = "obj_introtangle";
	global.__objectNames[159] = "obj_itembt";
	global.__objectNames[160] = "obj_kitchentable";
	global.__objectNames[161] = "obj_knife_pickup";
	global.__objectNames[162] = "obj_lasergen1";
	global.__objectNames[163] = "obj_lborder";
	global.__objectNames[164] = "obj_lchair";
	global.__objectNames[165] = "obj_loox";
	global.__objectNames[166] = "obj_mainchara";
	global.__objectNames[167] = "obj_markerA";
	global.__objectNames[168] = "obj_markerB";
	global.__objectNames[169] = "obj_markerC";
	global.__objectNames[170] = "obj_markerD";
	global.__objectNames[171] = "obj_markerX";
	global.__objectNames[172] = "obj_menumusictest";
	global.__objectNames[173] = "obj_migosp";
	global.__objectNames[174] = "obj_mirrorreflection";
	global.__objectNames[175] = "obj_moldsmal";
	global.__objectNames[176] = "obj_monsterparent";
	global.__objectNames[177] = "obj_mousehole";
	global.__objectNames[178] = "obj_musfadein";
	global.__objectNames[179] = "obj_musfadeout";
	global.__objectNames[180] = "obj_musicchecker";
	global.__objectNames[181] = "obj_napstablook";
	global.__objectNames[182] = "obj_napstablook1";
	global.__objectNames[183] = "obj_napstablook2";
	global.__objectNames[184] = "obj_nastrytree_bottom";
	global.__objectNames[185] = "obj_nastytree";
	global.__objectNames[186] = "OBJ_NOMSCWRITER";
	global.__objectNames[187] = "obj_npc_marker";
	global.__objectNames[188] = "obj_npctest";
	global.__objectNames[189] = "obj_overworldcontroller";
	global.__objectNames[190] = "obj_papyrussign";
	global.__objectNames[191] = "obj_pbflame";
	global.__objectNames[192] = "obj_persistentfader";
	global.__objectNames[193] = "obj_pie_pickup";
	global.__objectNames[194] = "obj_pillar_1";
	global.__objectNames[195] = "obj_plotswitch1";
	global.__objectNames[196] = "obj_plotswitch2";
	global.__objectNames[197] = "obj_plotswitch3";
	global.__objectNames[198] = "obj_plotwall_room";
	global.__objectNames[199] = "obj_plotwall1";
	global.__objectNames[200] = "obj_plotwall2";
	global.__objectNames[201] = "obj_plotwall3";
	global.__objectNames[202] = "obj_plotwall4";
	global.__objectNames[203] = "obj_plotwall5";
	global.__objectNames[204] = "obj_plotwall6";
	global.__objectNames[205] = "obj_pushrock1";
	global.__objectNames[206] = "obj_pushrock2";
	global.__objectNames[207] = "obj_pushrock3";
	global.__objectNames[208] = "obj_quittingmessage";
	global.__objectNames[209] = "obj_radialfakegen";
	global.__objectNames[210] = "obj_radialfakegenx";
	global.__objectNames[211] = "obj_rborder";
	global.__objectNames[212] = "obj_rchair";
	global.__objectNames[213] = "obj_readable";
	global.__objectNames[214] = "obj_readable_flowers1";
	global.__objectNames[215] = "obj_readable_plaque_1";
	global.__objectNames[216] = "obj_readable_plaque_2";
	global.__objectNames[217] = "obj_readable_room1";
	global.__objectNames[218] = "obj_readable_room2";
	global.__objectNames[219] = "obj_readable_room3";
	global.__objectNames[220] = "obj_readable_room4";
	global.__objectNames[221] = "obj_readable_sign1";
	global.__objectNames[222] = "obj_readable_sign2";
	global.__objectNames[223] = "obj_readable_switch1";
	global.__objectNames[224] = "obj_readablesolid";
	global.__objectNames[225] = "obj_redswitch_1";
	global.__objectNames[226] = "obj_ribbon_pickup";
	global.__objectNames[227] = "obj_rock_activator";
	global.__objectNames[228] = "obj_rotategen";
	global.__objectNames[229] = "obj_ruinsdoor1";
	global.__objectNames[230] = "obj_ruinsmusic";
	global.__objectNames[231] = "obj_sadmsggen";
	global.__objectNames[232] = "obj_sansbox";
	global.__objectNames[233] = "obj_savepoint";
	global.__objectNames[234] = "obj_screen";
	global.__objectNames[235] = "obj_sdl";
	global.__objectNames[236] = "obj_sdr";
	global.__objectNames[237] = "obj_shaker";
	global.__objectNames[238] = "obj_sign_room";
	global.__objectNames[239] = "obj_slice";
	global.__objectNames[240] = "obj_smallchair";
	global.__objectNames[241] = "obj_smallfrog";
	global.__objectNames[242] = "obj_smallweb";
	global.__objectNames[243] = "obj_sockdrawer";
	global.__objectNames[244] = "obj_solidlong";
	global.__objectNames[245] = "obj_solidnpcparent";
	global.__objectNames[246] = "obj_solidparent";
	global.__objectNames[247] = "obj_solidrailing";
	global.__objectNames[248] = "obj_solidrailing2";
	global.__objectNames[249] = "obj_solidrailing3";
	global.__objectNames[250] = "obj_solidsmall";
	global.__objectNames[251] = "obj_solidtall";
	global.__objectNames[252] = "obj_solidwide";
	global.__objectNames[253] = "obj_sparebt";
	global.__objectNames[254] = "obj_spared";
	global.__objectNames[255] = "obj_spellbt";
	global.__objectNames[256] = "obj_spikes_room";
	global.__objectNames[257] = "obj_spiketile1";
	global.__objectNames[258] = "obj_spiketile2";
	global.__objectNames[259] = "obj_staircollission";
	global.__objectNames[260] = "obj_stairstep";
	global.__objectNames[261] = "obj_stalkerflowey";
	global.__objectNames[262] = "obj_storagemenu";
	global.__objectNames[263] = "obj_sul";
	global.__objectNames[264] = "obj_sur";
	global.__objectNames[265] = "obj_switchadvice1";
	global.__objectNames[266] = "obj_switchadvice2";
	global.__objectNames[267] = "obj_switchbasic";
	global.__objectNames[268] = "obj_switchhelptrigger";
	global.__objectNames[269] = "obj_talkbt";
	global.__objectNames[270] = "obj_target";
	global.__objectNames[271] = "obj_targetchoice";
	global.__objectNames[272] = "obj_targetchoiceHITSEVERYONE";
	global.__objectNames[273] = "obj_tempblack";
	global.__objectNames[274] = "obj_testmonster";
	global.__objectNames[275] = "obj_theartshard";
	global.__objectNames[276] = "obj_time";
	global.__objectNames[277] = "obj_titleimage";
	global.__objectNames[278] = "obj_torbody";
	global.__objectNames[279] = "obj_torface";
	global.__objectNames[280] = "obj_torgen";
	global.__objectNames[281] = "obj_torgen_house1";
	global.__objectNames[282] = "obj_torhandhold1";
	global.__objectNames[283] = "obj_torheart";
	global.__objectNames[284] = "obj_torielboss";
	global.__objectNames[285] = "obj_torielcall1";
	global.__objectNames[286] = "obj_torielcall2";
	global.__objectNames[287] = "obj_torielcall3";
	global.__objectNames[288] = "obj_torielcall4";
	global.__objectNames[289] = "obj_torielcall5";
	global.__objectNames[290] = "obj_torielcutscene";
	global.__objectNames[291] = "obj_torieldisapprove";
	global.__objectNames[292] = "obj_torielflame_X";
	global.__objectNames[293] = "obj_torieltrigger1";
	global.__objectNames[294] = "obj_torieltrigger10";
	global.__objectNames[295] = "obj_torieltrigger11";
	global.__objectNames[296] = "obj_torieltrigger12";
	global.__objectNames[297] = "obj_torieltrigger2";
	global.__objectNames[298] = "obj_torieltrigger3";
	global.__objectNames[299] = "obj_torieltrigger4";
	global.__objectNames[300] = "obj_torieltrigger5";
	global.__objectNames[301] = "obj_torieltrigger6";
	global.__objectNames[302] = "obj_torieltrigger7";
	global.__objectNames[303] = "obj_torieltrigger8";
	global.__objectNames[304] = "obj_torieltrigger9";
	global.__objectNames[305] = "obj_torinteractable1";
	global.__objectNames[306] = "obj_torinteractable2";
	global.__objectNames[307] = "obj_torinteractable3";
	global.__objectNames[308] = "obj_torinteractable4";
	global.__objectNames[309] = "obj_torinteractable5";
	global.__objectNames[310] = "obj_torinteractable6";
	global.__objectNames[311] = "obj_torinteractable7";
	global.__objectNames[312] = "obj_toroverworld1";
	global.__objectNames[313] = "obj_toroverworld2";
	global.__objectNames[314] = "obj_toroverworld3";
	global.__objectNames[315] = "obj_toroverworld4";
	global.__objectNames[316] = "obj_toroverworld5";
	global.__objectNames[317] = "obj_toroverworld6";
	global.__objectNames[318] = "obj_toroverworld7";
	global.__objectNames[319] = "obj_transheart";
	global.__objectNames[320] = "obj_transitioner";
	global.__objectNames[321] = "obj_uborder";
	global.__objectNames[322] = "obj_uchair";
	global.__objectNames[323] = "obj_undertaletitle";
	global.__objectNames[324] = "obj_unfader";
	global.__objectNames[325] = "obj_vaporacquirer";
	global.__objectNames[326] = "obj_vaporized";
	global.__objectNames[327] = "obj_vaporized_old";
	global.__objectNames[328] = "obj_vaporizedspare";
	global.__objectNames[329] = "obj_vegetoid";
	global.__objectNames[330] = "obj_vegetoid_overworld";
	global.__objectNames[331] = "obj_wallswitchcut1";
	global.__objectNames[332] = "obj_wanderparent";
	global.__objectNames[333] = "obj_whimsun";
	global.__objectNames[334] = "obj_whitefader";
	global.__objectNames[335] = "obj_whtpxlgrav";
	global.__objectNames[336] = "obj_winkstar";
	global.__objectNames[337] = "OBJ_WRITER";
	global.__objectNames[338] = "OBJ_WRITERCREATOR";
	global.__objectNames[339] = "object59";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
